// New exercises sourced from the everkinetic image library.
// These are added to the exercise_library alongside the original 81 exercises.
// Each entry uses the display name derived from the image key.

export const IMAGE_EXERCISES: {
  name: string;
  category: string;
  muscleGroup: string;
  equipment: string;
  imageKey: string;
}[] = [
  { name: 'Ab Rollout On Knees With Barbell', category: 'Barbell', muscleGroup: 'Core', equipment: 'Barbell', imageKey: 'ab-rollout-on-knees-with-barbell' },
  { name: 'Air Bike', category: 'Cardio', muscleGroup: 'Cardio', equipment: 'Bike', imageKey: 'air-bike' },
  { name: 'Alternating Bicep Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'alternating-bicep-curl-with-dumbbell' },
  { name: 'Alternating Hammer Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'alternating-hammer-curl-with-dumbbell' },
  { name: 'Arnold Press', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'arnold-press' },
  { name: 'Back Extension Stability Ball', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Stability Ball', imageKey: 'back-extension-stability-ball' },
  { name: 'Back Flys Exercise Band', category: 'Cable', muscleGroup: 'Back', equipment: 'Band', imageKey: 'back-flys-exercise-band' },
  { name: 'Balance Board', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Balance Board', imageKey: 'balance-board' },
  { name: 'Ball Wall Circles', category: 'Bodyweight', muscleGroup: 'Shoulders', equipment: 'Wall Ball', imageKey: 'ball-wall-circles' },
  { name: 'Barbell Dead Lifts', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell', imageKey: 'barbell-dead-lifts' },
  { name: 'Barbell Front Raise Pullover', category: 'Barbell', muscleGroup: 'Shoulders', equipment: 'Barbell', imageKey: 'barbell-front-raise-pullover' },
  { name: 'Barbell Good Mornings', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell', imageKey: 'barbell-good-mornings' },
  { name: 'Barbell Lunges', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'barbell-lunges' },
  { name: 'Barbell Neck Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell', imageKey: 'barbell-neck-press' },
  { name: 'Barbell Shoulder Press', category: 'Barbell', muscleGroup: 'Shoulders', equipment: 'Barbell', imageKey: 'barbell-shoulder-press' },
  { name: 'Barbell Shrugs', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell', imageKey: 'barbell-shrugs' },
  { name: 'Barbell Squat', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'barbell-squat' },
  { name: 'Bench Dips', category: 'Bodyweight', muscleGroup: 'Arms', equipment: 'Bodyweight', imageKey: 'bench-dips' },
  { name: 'Bench Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell', imageKey: 'bench-press' },
  { name: 'Bench Press Dumbbell', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell', imageKey: 'bench-press-dumbbell' },
  { name: 'Bent Arm Pullover', category: 'Dumbbell', muscleGroup: 'Back', equipment: 'Dumbbell', imageKey: 'bent-arm-pullover' },
  { name: 'Bent Knee Hip Raise', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight', imageKey: 'bent-knee-hip-raise' },
  { name: 'Bent Over Lateral Cable Raises', category: 'Cable', muscleGroup: 'Shoulders', equipment: 'Cable', imageKey: 'bent-over-lateral-cable-raises' },
  { name: 'Bent Over Rear Deltoid Raise With Head On Bench', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'bent-over-rear-deltoid-raise-with-head-on-bench' },
  { name: 'Bicep Curl Lunge With Bowling Motion', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'bicep-curl-lunge-with-bowling-motion' },
  { name: 'Bicep Curl On Stability Ball With Leg Raised', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'bicep-curl-on-stability-ball-with-leg-raised' },
  { name: 'Bicep Curls With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'bicep-curls-with-barbell' },
  { name: 'Bicep Curl With Machine', category: 'Machine', muscleGroup: 'Arms', equipment: 'Machine', imageKey: 'bicep-curl-with-machine' },
  { name: 'Bicep Hammer Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'bicep-hammer-curl-with-dumbbell' },
  { name: 'Biceps Curl Reverse With Dumbbells', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'biceps-curl-reverse-with-dumbbells' },
  { name: 'Biceps Curl Seated On Stability Ball With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'biceps-curl-seated-on-stability-ball-with-dumbbell' },
  { name: 'Biceps Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'biceps-curl-with-dumbbell' },
  { name: 'Biceps Curl With Overhead Extension Using Dumbbells On Stability Ball', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'biceps-curl-with-overhead-extension-using-dumbbells-on-stability-ball' },
  { name: 'Body Leg Lifts', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight', imageKey: 'body-leg-lifts' },
  { name: 'Body Row', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight', imageKey: 'body-row' },
  { name: 'Bosu Ball Push Up', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight', imageKey: 'bosu-ball-push-up' },
  { name: 'Bridging', category: 'Bodyweight', muscleGroup: 'Legs', equipment: 'Bodyweight', imageKey: 'bridging' },
  { name: 'Butterfly Machine', category: 'Machine', muscleGroup: 'Chest', equipment: 'Machine', imageKey: 'butterfly-machine' },
  { name: 'Cable Crossover', category: 'Cable', muscleGroup: 'Chest', equipment: 'Cable', imageKey: 'cable-crossover' },
  { name: 'Cable Shoulder Shrugs', category: 'Cable', muscleGroup: 'Back', equipment: 'Cable', imageKey: 'cable-shoulder-shrugs' },
  { name: 'Calves Press On Leg Machine', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'calves-press-on-leg-machine' },
  { name: 'Chest Dips', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight', imageKey: 'chest-dips' },
  { name: 'Chin Ups', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight', imageKey: 'chin-ups' },
  { name: 'Close Grip Barbell Bench Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell', imageKey: 'close-grip-barbell-bench-press' },
  { name: 'Close Grip EZ Bar Curl With Barbell', category: 'EZ Bar', muscleGroup: 'Arms', equipment: 'EZ Bar', imageKey: 'close-grip-ez-bar-curl-with-barbell' },
  { name: 'Close Grip Standing Bicep Curls With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'close-grip-standing-bicep-curls-with-barbell' },
  { name: 'Close Triceps Pushup', category: 'Bodyweight', muscleGroup: 'Arms', equipment: 'Bodyweight', imageKey: 'close-triceps-pushup' },
  { name: 'Cross Body Hammer Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'cross-body-hammer-curl-with-dumbbell' },
  { name: 'Crossover Bands', category: 'Cable', muscleGroup: 'Chest', equipment: 'Band', imageKey: 'crossover-bands' },
  { name: 'Crunches', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight', imageKey: 'crunches' },
  { name: 'Crunches With Legs On Stability Ball', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Stability Ball', imageKey: 'crunches-with-legs-on-stability-ball' },
  { name: 'Cuban Dumbbell Press', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'cuban-dumbbell-press' },
  { name: 'Decline Barbell Bench Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell', imageKey: 'decline-barbell-bench-press' },
  { name: 'Decline Chest Press', category: 'Machine', muscleGroup: 'Chest', equipment: 'Machine', imageKey: 'decline-chest-press' },
  { name: 'Decline Close Grip Bench To Skull Crusher', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'decline-close-grip-bench-to-skull-crusher' },
  { name: 'Decline Dumbbell Bench Press', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell', imageKey: 'decline-dumbbell-bench-press' },
  { name: 'Decline Dumbbell Flys', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell', imageKey: 'decline-dumbbell-flys' },
  { name: 'Decline EZ Bar Triceps Extension With Barbell', category: 'EZ Bar', muscleGroup: 'Arms', equipment: 'EZ Bar', imageKey: 'decline-ez-bar-triceps-extension-with-barbell' },
  { name: 'Decline Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'decline-triceps-extension-with-dumbbell' },
  { name: 'Donkey Calf Raises', category: 'Bodyweight', muscleGroup: 'Legs', equipment: 'Bodyweight', imageKey: 'donkey-calf-raises' },
  { name: 'Drag Curl With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'drag-curl-with-barbell' },
  { name: 'Dumbbell Bent Arm Pullover', category: 'Dumbbell', muscleGroup: 'Back', equipment: 'Dumbbell', imageKey: 'dumbbell-bent-arm-pullover' },
  { name: 'Dumbbell Dead Lifts', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell', imageKey: 'dumbbell-dead-lifts' },
  { name: 'Dumbbell Flys', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell', imageKey: 'dumbbell-flys' },
  { name: 'Dumbbell Incline Bench Press', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell', imageKey: 'dumbbell-incline-bench-press' },
  { name: 'Dumbbell Lunges', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell', imageKey: 'dumbbell-lunges' },
  { name: 'Dumbbell Raise', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'dumbbell-raise' },
  { name: 'Dumbbell Shoulder Press', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'dumbbell-shoulder-press' },
  { name: 'Dumbbell Upright Rows', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'dumbbell-upright-rows' },
  { name: 'EZ Bar Curl With Barbell', category: 'EZ Bar', muscleGroup: 'Arms', equipment: 'EZ Bar', imageKey: 'ez-bar-curl-with-barbell' },
  { name: 'Flat Bench Cable Flys', category: 'Cable', muscleGroup: 'Chest', equipment: 'Cable', imageKey: 'flat-bench-cable-flys' },
  { name: 'Flat Bench Leg Raises', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight', imageKey: 'flat-bench-leg-raises' },
  { name: 'Flutter Kicks', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight', imageKey: 'flutter-kicks' },
  { name: 'Forward Lunge With Bicep Curl Using Dumbbell', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell', imageKey: 'forward-lunge-with-bicep-curl-using-dumbbell' },
  { name: 'Front Barbell Raises', category: 'Barbell', muscleGroup: 'Shoulders', equipment: 'Barbell', imageKey: 'front-barbell-raises' },
  { name: 'Front Cable Raises', category: 'Cable', muscleGroup: 'Shoulders', equipment: 'Cable', imageKey: 'front-cable-raises' },
  { name: 'Front Dumbbell Raise', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'front-dumbbell-raise' },
  { name: 'Front Raises', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'front-raises' },
  { name: 'Front Squat To Bench With Barbells', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'front-squat-to-bench-with-barbells' },
  { name: 'Front Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'front-squat-with-barbell' },
  { name: 'Gironda Sternum Chins', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight', imageKey: 'gironda-sternum-chins' },
  { name: 'Hack Squat Machine', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'hack-squat-machine' },
  { name: 'Hack Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'hack-squat-with-barbell' },
  { name: 'Hammer Curls With Rope And Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'hammer-curls-with-rope-and-cable' },
  { name: 'Hammer Grip Incline Bench Press', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell', imageKey: 'hammer-grip-incline-bench-press' },
  { name: 'High Cable Curls', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'high-cable-curls' },
  { name: 'Hip Adduction', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'hip-adduction' },
  { name: 'Hyperextensions', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight', imageKey: 'hyperextensions' },
  { name: 'Incline Bench Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell', imageKey: 'incline-bench-press' },
  { name: 'Incline Bench Press With Bands', category: 'Cable', muscleGroup: 'Chest', equipment: 'Band', imageKey: 'incline-bench-press-with-bands' },
  { name: 'Incline Cable Flys', category: 'Cable', muscleGroup: 'Chest', equipment: 'Cable', imageKey: 'incline-cable-flys' },
  { name: 'Incline Chest Press', category: 'Machine', muscleGroup: 'Chest', equipment: 'Machine', imageKey: 'incline-chest-press' },
  { name: 'Incline Dumbbell Flys', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell', imageKey: 'incline-dumbbell-flys' },
  { name: 'Incline Dumbbell Press', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell', imageKey: 'incline-dumbbell-press' },
  { name: 'Incline Pushdown With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'incline-pushdown-with-cable' },
  { name: 'Incline Shoulder Press Dumbbell', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'incline-shoulder-press-dumbbell' },
  { name: 'Incline Triceps Extensions With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'incline-triceps-extensions-with-dumbbell' },
  { name: 'Incline Triceps Extension With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'incline-triceps-extension-with-barbell' },
  { name: 'Incline Triceps Extension With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'incline-triceps-extension-with-cable' },
  { name: 'Internal Cable Rotation', category: 'Cable', muscleGroup: 'Shoulders', equipment: 'Cable', imageKey: 'internal-cable-rotation' },
  { name: 'Iron Cross With Dumbbells', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'iron-cross-with-dumbbells' },
  { name: 'Jefferson Squats With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'jefferson-squats-with-barbell' },
  { name: 'JM Press', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'jm-press' },
  { name: 'Kneeling Triceps Extension With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'kneeling-triceps-extension-with-cable' },
  { name: 'Kneeling Triceps Extension With Cable 2', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'kneeling-triceps-extension-with-cable-2' },
  { name: 'Lateral Dumbbell Raises', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'lateral-dumbbell-raises' },
  { name: 'Leg Extensions', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'leg-extensions' },
  { name: 'Leg Press', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'leg-press' },
  { name: 'Low Triceps Extension With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'low-triceps-extension-with-cable' },
  { name: 'Lying Close Grip Biceps Curls With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'lying-close-grip-biceps-curls-with-cable' },
  { name: 'Lying Close Grip Triceps Extension Behind The Head With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'lying-close-grip-triceps-extension-behind-the-head-with-barbell' },
  { name: 'Lying Close Grip Triceps Press To Chin With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'lying-close-grip-triceps-press-to-chin-with-barbell' },
  { name: 'Lying High Bench Biceps Curl With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'lying-high-bench-biceps-curl-with-barbell' },
  { name: 'Lying Leg Curl Machine', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'lying-leg-curl-machine' },
  { name: 'Lying One Arm Rear Lateral Raise', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'lying-one-arm-rear-lateral-raise' },
  { name: 'Lying Rear Lateral Raise', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'lying-rear-lateral-raise' },
  { name: 'Lying Squat', category: 'Bodyweight', muscleGroup: 'Legs', equipment: 'Bodyweight', imageKey: 'lying-squat' },
  { name: 'Lying Triceps Extension Across Face With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'lying-triceps-extension-across-face-with-dumbbell' },
  { name: 'Lying Triceps Extension With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'lying-triceps-extension-with-cable' },
  { name: 'Lying Triceps Extension With Dumbbells', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'lying-triceps-extension-with-dumbbells' },
  { name: 'Lying Triceps Press With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'lying-triceps-press-with-barbell' },
  { name: 'Lying Two Arm Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'lying-two-arm-triceps-extension-with-dumbbell' },
  { name: 'Machine Bench Press', category: 'Machine', muscleGroup: 'Chest', equipment: 'Machine', imageKey: 'machine-bench-press' },
  { name: 'Narrow Parallel Grip Chin Ups', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight', imageKey: 'narrow-parallel-grip-chin-ups' },
  { name: 'Narrow Stance Hack Squats', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'narrow-stance-hack-squats' },
  { name: 'Narrow Stance Leg Press', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'narrow-stance-leg-press' },
  { name: 'Narrow Stance Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'narrow-stance-squat-with-barbell' },
  { name: 'Old School Reverse Extensions', category: 'Bodyweight', muscleGroup: 'Legs', equipment: 'Bodyweight', imageKey: 'old-school-reverse-extensions' },
  { name: 'One Arm Barbell Floor Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell', imageKey: 'one-arm-barbell-floor-press' },
  { name: 'One Arm Bench Press', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell', imageKey: 'one-arm-bench-press' },
  { name: 'One Arm Bicep Curl With Olympic Bar Or Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'one-arm-bicep-curl-with-olympic-bar-or-barbell' },
  { name: 'One Arm Dumbbell Shoulder Press', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'one-arm-dumbbell-shoulder-press' },
  { name: 'One Armed Biased Push Up', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight', imageKey: 'one-armed-biased-push-up' },
  { name: 'One Arm Flat Bench Flys', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell', imageKey: 'one-arm-flat-bench-flys' },
  { name: 'One Arm Low Pulley Triceps Extension With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'one-arm-low-pulley-triceps-extension-with-cable' },
  { name: 'One Arm Preacher Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'one-arm-preacher-curl-with-dumbbell' },
  { name: 'One Arm Side Deadlift With Barbell', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell', imageKey: 'one-arm-side-deadlift-with-barbell' },
  { name: 'One Arm Snatch With Barbell', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell', imageKey: 'one-arm-snatch-with-barbell' },
  { name: 'One Arm Tricep Extension With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'one-arm-tricep-extension-with-cable' },
  { name: 'One Arm Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'one-arm-triceps-extension-with-dumbbell' },
  { name: 'One Arm Upright Row', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell', imageKey: 'one-arm-upright-row' },
  { name: 'One Legged Cable Kickback', category: 'Cable', muscleGroup: 'Legs', equipment: 'Cable', imageKey: 'one-legged-cable-kickback' },
  { name: 'One Leg Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'one-leg-squat-with-barbell' },
  { name: 'Overhead Curl With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'overhead-curl-with-cable' },
  { name: 'Overhead Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'overhead-squat-with-barbell' },
  { name: 'Pile Squat With Dumbbell', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell', imageKey: 'pile-squat-with-dumbbell' },
  { name: 'Preacher Curl With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'preacher-curl-with-barbell' },
  { name: 'Preacher Curl With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'preacher-curl-with-cable' },
  { name: 'Preacher Curl With Machine', category: 'Machine', muscleGroup: 'Arms', equipment: 'Machine', imageKey: 'preacher-curl-with-machine' },
  { name: 'Preacher Hammer Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'preacher-hammer-curl-with-dumbbell' },
  { name: 'Pullover Stability Ball Weight', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Stability Ball', imageKey: 'pullover-stability-ball-weight' },
  { name: 'Pull Ups', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight', imageKey: 'pull-ups' },
  { name: 'Push Up Feet Elevated', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight', imageKey: 'push-up-feet-elevated' },
  { name: 'Push Up Feet Elevated 2', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight', imageKey: 'push-up-feet-elevated-2' },
  { name: 'Push Ups', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight', imageKey: 'push-ups' },
  { name: 'Push Ups Close And Wide Hand Versions', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight', imageKey: 'push-ups-close-and-wide-hand-versions' },
  { name: 'Push Ups With Feet On Exercise Ball', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight', imageKey: 'push-ups-with-feet-on-exercise-ball' },
  { name: 'Quick Alternating Bicep Curls With Band', category: 'Cable', muscleGroup: 'Arms', equipment: 'Band', imageKey: 'quick-alternating-bicep-curls-with-band' },
  { name: 'Rear Deltoid Row Barbell', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell', imageKey: 'rear-deltoid-row-barbell' },
  { name: 'Rear Deltoid Row Dumbbell', category: 'Dumbbell', muscleGroup: 'Back', equipment: 'Dumbbell', imageKey: 'rear-deltoid-row-dumbbell' },
  { name: 'Rear Lunges With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'rear-lunges-with-barbell' },
  { name: 'Rear Lunges With Dumbbell', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell', imageKey: 'rear-lunges-with-dumbbell' },
  { name: 'Reverse Grips Bent Over Barbell Rows', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell', imageKey: 'reverse-grips-bent-over-barbell-rows' },
  { name: 'Reverse Grip Triceps Pushdown', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'reverse-grip-triceps-pushdown' },
  { name: 'Reverse Triceps Bench Press With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'reverse-triceps-bench-press-with-barbell' },
  { name: 'Rocking Standing Calf Raise With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'rocking-standing-calf-raise-with-barbell' },
  { name: 'Romanian Dead Lift', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'romanian-dead-lift' },
  { name: 'Seated Ab Crunch With Cable', category: 'Cable', muscleGroup: 'Core', equipment: 'Cable', imageKey: 'seated-ab-crunch-with-cable' },
  { name: 'Seated Bicep Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'seated-bicep-curl-with-dumbbell' },
  { name: 'Seated Cable Rows', category: 'Cable', muscleGroup: 'Back', equipment: 'Cable', imageKey: 'seated-cable-rows' },
  { name: 'Seated Calf Raise With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'seated-calf-raise-with-barbell' },
  { name: 'Seated Inner Biceps Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'seated-inner-biceps-curl-with-dumbbell' },
  { name: 'Seated Leg Curl', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'seated-leg-curl' },
  { name: 'Seated Military Press', category: 'Barbell', muscleGroup: 'Shoulders', equipment: 'Barbell', imageKey: 'seated-military-press' },
  { name: 'Seated One Arm Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'seated-one-arm-triceps-extension-with-dumbbell' },
  { name: 'Seated Overhead Triceps Extension With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'seated-overhead-triceps-extension-with-barbell' },
  { name: 'Seated Rear Lateral Cable Raise', category: 'Cable', muscleGroup: 'Shoulders', equipment: 'Cable', imageKey: 'seated-rear-lateral-cable-raise' },
  { name: 'Seated Shoulder Press Machine', category: 'Machine', muscleGroup: 'Shoulders', equipment: 'Machine', imageKey: 'seated-shoulder-press-machine' },
  { name: 'Seated Triceps Press With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'seated-triceps-press-with-dumbbell' },
  { name: 'Shoulder Shrugs', category: 'Dumbbell', muscleGroup: 'Back', equipment: 'Dumbbell', imageKey: 'shoulder-shrugs' },
  { name: 'Side Bend With Dumbbell', category: 'Dumbbell', muscleGroup: 'Core', equipment: 'Dumbbell', imageKey: 'side-bend-with-dumbbell' },
  { name: 'Side Plank', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight', imageKey: 'side-plank' },
  { name: 'Side Squats With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'side-squats-with-barbell' },
  { name: 'Single Arm Supinated Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'single-arm-supinated-triceps-extension-with-dumbbell' },
  { name: 'Single Arm Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'single-arm-triceps-extension-with-dumbbell' },
  { name: 'Single Leg Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'single-leg-squat-with-barbell' },
  { name: 'Smith Machine Bench Press', category: 'Machine', muscleGroup: 'Chest', equipment: 'Machine', imageKey: 'smith-machine-bench-press' },
  { name: 'Smith Machine Dead Lifts', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine', imageKey: 'smith-machine-dead-lifts' },
  { name: 'Smith Machine Good Mornings', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine', imageKey: 'smith-machine-good-mornings' },
  { name: 'Smith Machine Hack Squat', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'smith-machine-hack-squat' },
  { name: 'Smith Machine Incline Bench Press', category: 'Machine', muscleGroup: 'Chest', equipment: 'Machine', imageKey: 'smith-machine-incline-bench-press' },
  { name: 'Smith Machine Rear Deltoid Row', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine', imageKey: 'smith-machine-rear-deltoid-row' },
  { name: 'Smith Machine Reverse Calf Raises', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'smith-machine-reverse-calf-raises' },
  { name: 'Smith Machine Shoulder Shrugs', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine', imageKey: 'smith-machine-shoulder-shrugs' },
  { name: 'Smith Machine Squats', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'smith-machine-squats' },
  { name: 'Smith Machine Upright Row', category: 'Machine', muscleGroup: 'Shoulders', equipment: 'Machine', imageKey: 'smith-machine-upright-row' },
  { name: 'Speed Squats With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'speed-squats-with-barbell' },
  { name: 'Spider Curl With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'spider-curl-with-barbell' },
  { name: 'Squats Using Dumbbells', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell', imageKey: 'squats-using-dumbbells' },
  { name: 'Squats With Exercise Bands', category: 'Cable', muscleGroup: 'Legs', equipment: 'Band', imageKey: 'squats-with-exercise-bands' },
  { name: 'Squat To Bench With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'squat-to-bench-with-barbell' },
  { name: 'Squat To Bench With Dumbbells', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell', imageKey: 'squat-to-bench-with-dumbbells' },
  { name: 'Standing Barbell Calf Raise', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'standing-barbell-calf-raise' },
  { name: 'Standing Biceps Curl With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'standing-biceps-curl-with-cable' },
  { name: 'Standing Calf Raises Using Machine', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'standing-calf-raises-using-machine' },
  { name: 'Standing Inner Biceps Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'standing-inner-biceps-curl-with-dumbbell' },
  { name: 'Standing Leg Curls', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'standing-leg-curls' },
  { name: 'Standing One Arm Bicep Curl With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'standing-one-arm-bicep-curl-with-cable' },
  { name: 'Standing One Arm Curl Over Incline Bench With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'standing-one-arm-curl-over-incline-bench-with-dumbbell' },
  { name: 'Standing One Arm Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'standing-one-arm-triceps-extension-with-dumbbell' },
  { name: 'Standing Overhead Triceps Extension With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'standing-overhead-triceps-extension-with-barbell' },
  { name: 'Standing Triceps Extension', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'standing-triceps-extension' },
  { name: 'Standing Triceps Extension 2', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'standing-triceps-extension-2' },
  { name: 'Static Neck Flexion Extension', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight', imageKey: 'static-neck-flexion-extension' },
  { name: 'Static Neck Side Flexion', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight', imageKey: 'static-neck-side-flexion' },
  { name: 'Stationary Abdominal Draw In', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight', imageKey: 'stationary-abdominal-draw-in' },
  { name: 'Step Up Single Leg Balance With Bicep Curl Using Dumbbells', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell', imageKey: 'step-up-single-leg-balance-with-bicep-curl-using-dumbbells' },
  { name: 'Step Ups With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'step-ups-with-barbell' },
  { name: 'Step Ups With Dumbbells', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell', imageKey: 'step-ups-with-dumbbells' },
  { name: 'Stork Stance Bicep Curl With Dumbbells', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'stork-stance-bicep-curl-with-dumbbells' },
  { name: 'Straight Arm Dumbbell Pullover', category: 'Dumbbell', muscleGroup: 'Back', equipment: 'Dumbbell', imageKey: 'straight-arm-dumbbell-pullover' },
  { name: 'Straight Arm Push Down', category: 'Cable', muscleGroup: 'Back', equipment: 'Cable', imageKey: 'straight-arm-push-down' },
  { name: 'Supermans', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight', imageKey: 'supermans' },
  { name: 'Tate Press', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'tate-press' },
  { name: 'T Bar Rows', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell', imageKey: 't-bar-rows' },
  { name: 'Thigh Abductor', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'thigh-abductor' },
  { name: 'Thigh Adductor', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine', imageKey: 'thigh-adductor' },
  { name: 'Tricep Dips', category: 'Bodyweight', muscleGroup: 'Arms', equipment: 'Bodyweight', imageKey: 'tricep-dips' },
  { name: 'Tricep Dips Using Body Weight', category: 'Bodyweight', muscleGroup: 'Arms', equipment: 'Bodyweight', imageKey: 'tricep-dips-using-body-weight' },
  { name: 'Triceps Extensions Using Machine', category: 'Machine', muscleGroup: 'Arms', equipment: 'Machine', imageKey: 'triceps-extensions-using-machine' },
  { name: 'Triceps Pushdown With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'triceps-pushdown-with-cable' },
  { name: 'Triceps Pushdown With Rope And Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'triceps-pushdown-with-rope-and-cable' },
  { name: 'Triceps Pushdown With V Bar And Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable', imageKey: 'triceps-pushdown-with-v-bar-and-cable' },
  { name: 'Two Arm Preacher Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'two-arm-preacher-curl-with-dumbbell' },
  { name: 'Underhand Pull Down', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine', imageKey: 'underhand-pull-down' },
  { name: 'Underhand Pull Downs', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine', imageKey: 'underhand-pull-downs' },
  { name: 'Upright Band Rows', category: 'Cable', muscleGroup: 'Shoulders', equipment: 'Band', imageKey: 'upright-band-rows' },
  { name: 'Upright Barbell Rows', category: 'Barbell', muscleGroup: 'Shoulders', equipment: 'Barbell', imageKey: 'upright-barbell-rows' },
  { name: 'Upright Cable Row', category: 'Cable', muscleGroup: 'Shoulders', equipment: 'Cable', imageKey: 'upright-cable-row' },
  { name: 'V Bar Pull Down', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine', imageKey: 'v-bar-pull-down' },
  { name: 'Walking Lunges', category: 'Bodyweight', muscleGroup: 'Legs', equipment: 'Bodyweight', imageKey: 'walking-lunges' },
  { name: 'Weighted Sissy Squat With Weight Plate', category: 'Bodyweight', muscleGroup: 'Legs', equipment: 'Bodyweight', imageKey: 'weighted-sissy-squat-with-weight-plate' },
  { name: 'Wide Grip Bench Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell', imageKey: 'wide-grip-bench-press' },
  { name: 'Wide Grip Chin Up', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight', imageKey: 'wide-grip-chin-up' },
  { name: 'Wide Grip Decline Barbell Pullover', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell', imageKey: 'wide-grip-decline-barbell-pullover' },
  { name: 'Wide Grip Decline Bench Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell', imageKey: 'wide-grip-decline-bench-press' },
  { name: 'Wide Grip Lat Pull Down', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine', imageKey: 'wide-grip-lat-pull-down' },
  { name: 'Wide Grip Standing Biceps Curl With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell', imageKey: 'wide-grip-standing-biceps-curl-with-barbell' },
  { name: 'Wide Stance Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'wide-stance-squat-with-barbell' },
  { name: 'Zecher Squats', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell', imageKey: 'zecher-squats' },
  { name: 'Zottman Curl With Dumbbells', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'zottman-curl-with-dumbbells' },
  { name: 'Zottman Preacher Curl With Dumbbells', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell', imageKey: 'zottman-preacher-curl-with-dumbbells' },
];
