// Master exercise metadata — source of truth for all 252 image-library exercises.
// Used by process-exercise-images.js and db.ts seed expansion.
// Each entry: { imageKey, displayName, category, muscleGroup, equipment }

const exercises = [
  { imageKey: 'ab-rollout-on-knees-with-barbell', displayName: 'Ab Rollout On Knees With Barbell', category: 'Barbell', muscleGroup: 'Core', equipment: 'Barbell' },
  { imageKey: 'air-bike', displayName: 'Air Bike', category: 'Cardio', muscleGroup: 'Cardio', equipment: 'Bike' },
  { imageKey: 'alternating-bicep-curl-with-dumbbell', displayName: 'Alternating Bicep Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'alternating-hammer-curl-with-dumbbell', displayName: 'Alternating Hammer Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'arnold-press', displayName: 'Arnold Press', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'back-extension-stability-ball', displayName: 'Back Extension Stability Ball', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Stability Ball' },
  { imageKey: 'back-flys-exercise-band', displayName: 'Back Flys Exercise Band', category: 'Cable', muscleGroup: 'Back', equipment: 'Band' },
  { imageKey: 'balance-board', displayName: 'Balance Board', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Balance Board' },
  { imageKey: 'ball-wall-circles', displayName: 'Ball Wall Circles', category: 'Bodyweight', muscleGroup: 'Shoulders', equipment: 'Wall Ball' },
  { imageKey: 'barbell-dead-lifts', displayName: 'Barbell Dead Lifts', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell' },
  { imageKey: 'barbell-front-raise-pullover', displayName: 'Barbell Front Raise Pullover', category: 'Barbell', muscleGroup: 'Shoulders', equipment: 'Barbell' },
  { imageKey: 'barbell-good-mornings', displayName: 'Barbell Good Mornings', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell' },
  { imageKey: 'barbell-lunges', displayName: 'Barbell Lunges', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'barbell-neck-press', displayName: 'Barbell Neck Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell' },
  { imageKey: 'barbell-shoulder-press', displayName: 'Barbell Shoulder Press', category: 'Barbell', muscleGroup: 'Shoulders', equipment: 'Barbell' },
  { imageKey: 'barbell-shrugs', displayName: 'Barbell Shrugs', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell' },
  { imageKey: 'barbell-squat', displayName: 'Barbell Squat', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'bench-dips', displayName: 'Bench Dips', category: 'Bodyweight', muscleGroup: 'Arms', equipment: 'Bodyweight' },
  { imageKey: 'bench-press', displayName: 'Bench Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell' },
  { imageKey: 'bench-press-dumbbell', displayName: 'Bench Press Dumbbell', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell' },
  { imageKey: 'bent-arm-pullover', displayName: 'Bent Arm Pullover', category: 'Dumbbell', muscleGroup: 'Back', equipment: 'Dumbbell' },
  { imageKey: 'bent-knee-hip-raise', displayName: 'Bent Knee Hip Raise', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight' },
  { imageKey: 'bent-over-lateral-cable-raises', displayName: 'Bent Over Lateral Cable Raises', category: 'Cable', muscleGroup: 'Shoulders', equipment: 'Cable' },
  { imageKey: 'bent-over-rear-deltoid-raise-with-head-on-bench', displayName: 'Bent Over Rear Deltoid Raise With Head On Bench', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'bicep-curl-lunge-with-bowling-motion', displayName: 'Bicep Curl Lunge With Bowling Motion', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'bicep-curl-on-stability-ball-with-leg-raised', displayName: 'Bicep Curl On Stability Ball With Leg Raised', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'bicep-curls-with-barbell', displayName: 'Bicep Curls With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'bicep-curl-with-machine', displayName: 'Bicep Curl With Machine', category: 'Machine', muscleGroup: 'Arms', equipment: 'Machine' },
  { imageKey: 'bicep-hammer-curl-with-dumbbell', displayName: 'Bicep Hammer Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'biceps-curl-reverse-with-dumbbells', displayName: 'Biceps Curl Reverse With Dumbbells', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'biceps-curl-seated-on-stability-ball-with-dumbbell', displayName: 'Biceps Curl Seated On Stability Ball With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'biceps-curl-with-dumbbell', displayName: 'Biceps Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'biceps-curl-with-overhead-extension-using-dumbbells-on-stability-ball', displayName: 'Biceps Curl With Overhead Extension Using Dumbbells On Stability Ball', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'body-leg-lifts', displayName: 'Body Leg Lifts', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight' },
  { imageKey: 'body-row', displayName: 'Body Row', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight' },
  { imageKey: 'bosu-ball-push-up', displayName: 'Bosu Ball Push Up', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight' },
  { imageKey: 'bridging', displayName: 'Bridging', category: 'Bodyweight', muscleGroup: 'Legs', equipment: 'Bodyweight' },
  { imageKey: 'butterfly-machine', displayName: 'Butterfly Machine', category: 'Machine', muscleGroup: 'Chest', equipment: 'Machine' },
  { imageKey: 'cable-crossover', displayName: 'Cable Crossover', category: 'Cable', muscleGroup: 'Chest', equipment: 'Cable' },
  { imageKey: 'cable-shoulder-shrugs', displayName: 'Cable Shoulder Shrugs', category: 'Cable', muscleGroup: 'Back', equipment: 'Cable' },
  { imageKey: 'calves-press-on-leg-machine', displayName: 'Calves Press On Leg Machine', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'chest-dips', displayName: 'Chest Dips', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight' },
  { imageKey: 'chin-ups', displayName: 'Chin Ups', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight' },
  { imageKey: 'close-grip-barbell-bench-press', displayName: 'Close Grip Barbell Bench Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell' },
  { imageKey: 'close-grip-ez-bar-curl-with-barbell', displayName: 'Close Grip EZ Bar Curl With Barbell', category: 'EZ Bar', muscleGroup: 'Arms', equipment: 'EZ Bar' },
  { imageKey: 'close-grip-standing-bicep-curls-with-barbell', displayName: 'Close Grip Standing Bicep Curls With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'close-triceps-pushup', displayName: 'Close Triceps Pushup', category: 'Bodyweight', muscleGroup: 'Arms', equipment: 'Bodyweight' },
  { imageKey: 'cross-body-hammer-curl-with-dumbbell', displayName: 'Cross Body Hammer Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'crossover-bands', displayName: 'Crossover Bands', category: 'Cable', muscleGroup: 'Chest', equipment: 'Band' },
  { imageKey: 'crunches', displayName: 'Crunches', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight' },
  { imageKey: 'crunches-with-legs-on-stability-ball', displayName: 'Crunches With Legs On Stability Ball', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Stability Ball' },
  { imageKey: 'cuban-dumbbell-press', displayName: 'Cuban Dumbbell Press', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'decline-barbell-bench-press', displayName: 'Decline Barbell Bench Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell' },
  { imageKey: 'decline-chest-press', displayName: 'Decline Chest Press', category: 'Machine', muscleGroup: 'Chest', equipment: 'Machine' },
  { imageKey: 'decline-close-grip-bench-to-skull-crusher', displayName: 'Decline Close Grip Bench To Skull Crusher', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'decline-dumbbell-bench-press', displayName: 'Decline Dumbbell Bench Press', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell' },
  { imageKey: 'decline-dumbbell-flys', displayName: 'Decline Dumbbell Flys', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell' },
  { imageKey: 'decline-ez-bar-triceps-extension-with-barbell', displayName: 'Decline EZ Bar Triceps Extension With Barbell', category: 'EZ Bar', muscleGroup: 'Arms', equipment: 'EZ Bar' },
  { imageKey: 'decline-triceps-extension-with-dumbbell', displayName: 'Decline Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'donkey-calf-raises', displayName: 'Donkey Calf Raises', category: 'Bodyweight', muscleGroup: 'Legs', equipment: 'Bodyweight' },
  { imageKey: 'drag-curl-with-barbell', displayName: 'Drag Curl With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'dumbbell-bent-arm-pullover', displayName: 'Dumbbell Bent Arm Pullover', category: 'Dumbbell', muscleGroup: 'Back', equipment: 'Dumbbell' },
  { imageKey: 'dumbbell-dead-lifts', displayName: 'Dumbbell Dead Lifts', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell' },
  { imageKey: 'dumbbell-flys', displayName: 'Dumbbell Flys', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell' },
  { imageKey: 'dumbbell-incline-bench-press', displayName: 'Dumbbell Incline Bench Press', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell' },
  { imageKey: 'dumbbell-lunges', displayName: 'Dumbbell Lunges', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell' },
  { imageKey: 'dumbbell-raise', displayName: 'Dumbbell Raise', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'dumbbell-shoulder-press', displayName: 'Dumbbell Shoulder Press', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'dumbbell-upright-rows', displayName: 'Dumbbell Upright Rows', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'ez-bar-curl-with-barbell', displayName: 'EZ Bar Curl With Barbell', category: 'EZ Bar', muscleGroup: 'Arms', equipment: 'EZ Bar' },
  { imageKey: 'flat-bench-cable-flys', displayName: 'Flat Bench Cable Flys', category: 'Cable', muscleGroup: 'Chest', equipment: 'Cable' },
  { imageKey: 'flat-bench-leg-raises', displayName: 'Flat Bench Leg Raises', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight' },
  { imageKey: 'flutter-kicks', displayName: 'Flutter Kicks', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight' },
  { imageKey: 'forward-lunge-with-bicep-curl-using-dumbbell', displayName: 'Forward Lunge With Bicep Curl Using Dumbbell', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell' },
  { imageKey: 'front-barbell-raises', displayName: 'Front Barbell Raises', category: 'Barbell', muscleGroup: 'Shoulders', equipment: 'Barbell' },
  { imageKey: 'front-cable-raises', displayName: 'Front Cable Raises', category: 'Cable', muscleGroup: 'Shoulders', equipment: 'Cable' },
  { imageKey: 'front-dumbbell-raise', displayName: 'Front Dumbbell Raise', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'front-raises', displayName: 'Front Raises', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'front-squat-to-bench-with-barbells', displayName: 'Front Squat To Bench With Barbells', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'front-squat-with-barbell', displayName: 'Front Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'gironda-sternum-chins', displayName: 'Gironda Sternum Chins', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight' },
  { imageKey: 'hack-squat-machine', displayName: 'Hack Squat Machine', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'hack-squat-with-barbell', displayName: 'Hack Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'hammer-curls-with-rope-and-cable', displayName: 'Hammer Curls With Rope And Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'hammer-grip-incline-bench-press', displayName: 'Hammer Grip Incline Bench Press', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell' },
  { imageKey: 'high-cable-curls', displayName: 'High Cable Curls', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'hip-adduction', displayName: 'Hip Adduction', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'hyperextensions', displayName: 'Hyperextensions', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight' },
  { imageKey: 'incline-bench-press', displayName: 'Incline Bench Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell' },
  { imageKey: 'incline-bench-press-with-bands', displayName: 'Incline Bench Press With Bands', category: 'Cable', muscleGroup: 'Chest', equipment: 'Band' },
  { imageKey: 'incline-cable-flys', displayName: 'Incline Cable Flys', category: 'Cable', muscleGroup: 'Chest', equipment: 'Cable' },
  { imageKey: 'incline-chest-press', displayName: 'Incline Chest Press', category: 'Machine', muscleGroup: 'Chest', equipment: 'Machine' },
  { imageKey: 'incline-dumbbell-flys', displayName: 'Incline Dumbbell Flys', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell' },
  { imageKey: 'incline-dumbbell-press', displayName: 'Incline Dumbbell Press', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell' },
  { imageKey: 'incline-pushdown-with-cable', displayName: 'Incline Pushdown With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'incline-shoulder-press-dumbbell', displayName: 'Incline Shoulder Press Dumbbell', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'incline-triceps-extensions-with-dumbbell', displayName: 'Incline Triceps Extensions With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'incline-triceps-extension-with-barbell', displayName: 'Incline Triceps Extension With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'incline-triceps-extension-with-cable', displayName: 'Incline Triceps Extension With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'internal-cable-rotation', displayName: 'Internal Cable Rotation', category: 'Cable', muscleGroup: 'Shoulders', equipment: 'Cable' },
  { imageKey: 'iron-cross-with-dumbbells', displayName: 'Iron Cross With Dumbbells', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'jefferson-squats-with-barbell', displayName: 'Jefferson Squats With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'jm-press', displayName: 'JM Press', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'kneeling-triceps-extension-with-cable', displayName: 'Kneeling Triceps Extension With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'kneeling-triceps-extension-with-cable-2', displayName: 'Kneeling Triceps Extension With Cable 2', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'lateral-dumbbell-raises', displayName: 'Lateral Dumbbell Raises', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'leg-extensions', displayName: 'Leg Extensions', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'leg-press', displayName: 'Leg Press', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'low-triceps-extension-with-cable', displayName: 'Low Triceps Extension With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'lying-close-grip-biceps-curls-with-cable', displayName: 'Lying Close Grip Biceps Curls With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'lying-close-grip-triceps-extension-behind-the-head-with-barbell', displayName: 'Lying Close Grip Triceps Extension Behind The Head With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'lying-close-grip-triceps-press-to-chin-with-barbell', displayName: 'Lying Close Grip Triceps Press To Chin With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'lying-high-bench-biceps-curl-with-barbell', displayName: 'Lying High Bench Biceps Curl With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'lying-leg-curl-machine', displayName: 'Lying Leg Curl Machine', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'lying-one-arm-rear-lateral-raise', displayName: 'Lying One Arm Rear Lateral Raise', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'lying-rear-lateral-raise', displayName: 'Lying Rear Lateral Raise', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'lying-squat', displayName: 'Lying Squat', category: 'Bodyweight', muscleGroup: 'Legs', equipment: 'Bodyweight' },
  { imageKey: 'lying-triceps-extension-across-face-with-dumbbell', displayName: 'Lying Triceps Extension Across Face With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'lying-triceps-extension-with-cable', displayName: 'Lying Triceps Extension With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'lying-triceps-extension-with-dumbbells', displayName: 'Lying Triceps Extension With Dumbbells', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'lying-triceps-press-with-barbell', displayName: 'Lying Triceps Press With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'lying-two-arm-triceps-extension-with-dumbbell', displayName: 'Lying Two Arm Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'machine-bench-press', displayName: 'Machine Bench Press', category: 'Machine', muscleGroup: 'Chest', equipment: 'Machine' },
  { imageKey: 'narrow-parallel-grip-chin-ups', displayName: 'Narrow Parallel Grip Chin Ups', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight' },
  { imageKey: 'narrow-stance-hack-squats', displayName: 'Narrow Stance Hack Squats', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'narrow-stance-leg-press', displayName: 'Narrow Stance Leg Press', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'narrow-stance-squat-with-barbell', displayName: 'Narrow Stance Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'old-school-reverse-extensions', displayName: 'Old School Reverse Extensions', category: 'Bodyweight', muscleGroup: 'Legs', equipment: 'Bodyweight' },
  { imageKey: 'one-arm-barbell-floor-press', displayName: 'One Arm Barbell Floor Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell' },
  { imageKey: 'one-arm-bench-press', displayName: 'One Arm Bench Press', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell' },
  { imageKey: 'one-arm-bicep-curl-with-olympic-bar-or-barbell', displayName: 'One Arm Bicep Curl With Olympic Bar Or Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'one-arm-dumbbell-shoulder-press', displayName: 'One Arm Dumbbell Shoulder Press', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'one-armed-biased-push-up', displayName: 'One Armed Biased Push Up', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight' },
  { imageKey: 'one-arm-flat-bench-flys', displayName: 'One Arm Flat Bench Flys', category: 'Dumbbell', muscleGroup: 'Chest', equipment: 'Dumbbell' },
  { imageKey: 'one-arm-low-pulley-triceps-extension-with-cable', displayName: 'One Arm Low Pulley Triceps Extension With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'one-arm-preacher-curl-with-dumbbell', displayName: 'One Arm Preacher Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'one-arm-side-deadlift-with-barbell', displayName: 'One Arm Side Deadlift With Barbell', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell' },
  { imageKey: 'one-arm-snatch-with-barbell', displayName: 'One Arm Snatch With Barbell', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell' },
  { imageKey: 'one-arm-tricep-extension-with-cable', displayName: 'One Arm Tricep Extension With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'one-arm-triceps-extension-with-dumbbell', displayName: 'One Arm Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'one-arm-upright-row', displayName: 'One Arm Upright Row', category: 'Dumbbell', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
  { imageKey: 'one-legged-cable-kickback', displayName: 'One Legged Cable Kickback', category: 'Cable', muscleGroup: 'Legs', equipment: 'Cable' },
  { imageKey: 'one-leg-squat-with-barbell', displayName: 'One Leg Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'overhead-curl-with-cable', displayName: 'Overhead Curl With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'overhead-squat-with-barbell', displayName: 'Overhead Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'pile-squat-with-dumbbell', displayName: 'Pile Squat With Dumbbell', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell' },
  { imageKey: 'preacher-curl-with-barbell', displayName: 'Preacher Curl With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'preacher-curl-with-cable', displayName: 'Preacher Curl With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'preacher-curl-with-machine', displayName: 'Preacher Curl With Machine', category: 'Machine', muscleGroup: 'Arms', equipment: 'Machine' },
  { imageKey: 'preacher-hammer-curl-with-dumbbell', displayName: 'Preacher Hammer Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'pullover-stability-ball-weight', displayName: 'Pullover Stability Ball Weight', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Stability Ball' },
  { imageKey: 'pull-ups', displayName: 'Pull Ups', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight' },
  { imageKey: 'push-up-feet-elevated', displayName: 'Push Up Feet Elevated', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight' },
  { imageKey: 'push-up-feet-elevated-2', displayName: 'Push Up Feet Elevated 2', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight' },
  { imageKey: 'push-ups', displayName: 'Push Ups', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight' },
  { imageKey: 'push-ups-close-and-wide-hand-versions', displayName: 'Push Ups Close And Wide Hand Versions', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight' },
  { imageKey: 'push-ups-with-feet-on-exercise-ball', displayName: 'Push Ups With Feet On Exercise Ball', category: 'Bodyweight', muscleGroup: 'Chest', equipment: 'Bodyweight' },
  { imageKey: 'quick-alternating-bicep-curls-with-band', displayName: 'Quick Alternating Bicep Curls With Band', category: 'Cable', muscleGroup: 'Arms', equipment: 'Band' },
  { imageKey: 'rear-deltoid-row-barbell', displayName: 'Rear Deltoid Row Barbell', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell' },
  { imageKey: 'rear-deltoid-row-dumbbell', displayName: 'Rear Deltoid Row Dumbbell', category: 'Dumbbell', muscleGroup: 'Back', equipment: 'Dumbbell' },
  { imageKey: 'rear-lunges-with-barbell', displayName: 'Rear Lunges With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'rear-lunges-with-dumbbell', displayName: 'Rear Lunges With Dumbbell', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell' },
  { imageKey: 'reverse-grips-bent-over-barbell-rows', displayName: 'Reverse Grips Bent Over Barbell Rows', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell' },
  { imageKey: 'reverse-grip-triceps-pushdown', displayName: 'Reverse Grip Triceps Pushdown', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'reverse-triceps-bench-press-with-barbell', displayName: 'Reverse Triceps Bench Press With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'rocking-standing-calf-raise-with-barbell', displayName: 'Rocking Standing Calf Raise With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'romanian-dead-lift', displayName: 'Romanian Dead Lift', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'seated-ab-crunch-with-cable', displayName: 'Seated Ab Crunch With Cable', category: 'Cable', muscleGroup: 'Core', equipment: 'Cable' },
  { imageKey: 'seated-bicep-curl-with-dumbbell', displayName: 'Seated Bicep Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'seated-cable-rows', displayName: 'Seated Cable Rows', category: 'Cable', muscleGroup: 'Back', equipment: 'Cable' },
  { imageKey: 'seated-calf-raise-with-barbell', displayName: 'Seated Calf Raise With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'seated-inner-biceps-curl-with-dumbbell', displayName: 'Seated Inner Biceps Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'seated-leg-curl', displayName: 'Seated Leg Curl', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'seated-military-press', displayName: 'Seated Military Press', category: 'Barbell', muscleGroup: 'Shoulders', equipment: 'Barbell' },
  { imageKey: 'seated-one-arm-triceps-extension-with-dumbbell', displayName: 'Seated One Arm Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'seated-overhead-triceps-extension-with-barbell', displayName: 'Seated Overhead Triceps Extension With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'seated-rear-lateral-cable-raise', displayName: 'Seated Rear Lateral Cable Raise', category: 'Cable', muscleGroup: 'Shoulders', equipment: 'Cable' },
  { imageKey: 'seated-shoulder-press-machine', displayName: 'Seated Shoulder Press Machine', category: 'Machine', muscleGroup: 'Shoulders', equipment: 'Machine' },
  { imageKey: 'seated-triceps-press-with-dumbbell', displayName: 'Seated Triceps Press With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'shoulder-shrugs', displayName: 'Shoulder Shrugs', category: 'Dumbbell', muscleGroup: 'Back', equipment: 'Dumbbell' },
  { imageKey: 'side-bend-with-dumbbell', displayName: 'Side Bend With Dumbbell', category: 'Dumbbell', muscleGroup: 'Core', equipment: 'Dumbbell' },
  { imageKey: 'side-plank', displayName: 'Side Plank', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight' },
  { imageKey: 'side-squats-with-barbell', displayName: 'Side Squats With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'single-arm-supinated-triceps-extension-with-dumbbell', displayName: 'Single Arm Supinated Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'single-arm-triceps-extension-with-dumbbell', displayName: 'Single Arm Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'single-leg-squat-with-barbell', displayName: 'Single Leg Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'smith-machine-bench-press', displayName: 'Smith Machine Bench Press', category: 'Machine', muscleGroup: 'Chest', equipment: 'Machine' },
  { imageKey: 'smith-machine-dead-lifts', displayName: 'Smith Machine Dead Lifts', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine' },
  { imageKey: 'smith-machine-good-mornings', displayName: 'Smith Machine Good Mornings', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine' },
  { imageKey: 'smith-machine-hack-squat', displayName: 'Smith Machine Hack Squat', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'smith-machine-incline-bench-press', displayName: 'Smith Machine Incline Bench Press', category: 'Machine', muscleGroup: 'Chest', equipment: 'Machine' },
  { imageKey: 'smith-machine-rear-deltoid-row', displayName: 'Smith Machine Rear Deltoid Row', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine' },
  { imageKey: 'smith-machine-reverse-calf-raises', displayName: 'Smith Machine Reverse Calf Raises', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'smith-machine-shoulder-shrugs', displayName: 'Smith Machine Shoulder Shrugs', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine' },
  { imageKey: 'smith-machine-squats', displayName: 'Smith Machine Squats', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'smith-machine-upright-row', displayName: 'Smith Machine Upright Row', category: 'Machine', muscleGroup: 'Shoulders', equipment: 'Machine' },
  { imageKey: 'speed-squats-with-barbell', displayName: 'Speed Squats With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'spider-curl-with-barbell', displayName: 'Spider Curl With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'squats-using-dumbbells', displayName: 'Squats Using Dumbbells', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell' },
  { imageKey: 'squats-with-exercise-bands', displayName: 'Squats With Exercise Bands', category: 'Cable', muscleGroup: 'Legs', equipment: 'Band' },
  { imageKey: 'squat-to-bench-with-barbell', displayName: 'Squat To Bench With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'squat-to-bench-with-dumbbells', displayName: 'Squat To Bench With Dumbbells', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell' },
  { imageKey: 'standing-barbell-calf-raise', displayName: 'Standing Barbell Calf Raise', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'standing-biceps-curl-with-cable', displayName: 'Standing Biceps Curl With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'standing-calf-raises-using-machine', displayName: 'Standing Calf Raises Using Machine', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'standing-inner-biceps-curl-with-dumbbell', displayName: 'Standing Inner Biceps Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'standing-leg-curls', displayName: 'Standing Leg Curls', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'standing-one-arm-bicep-curl-with-cable', displayName: 'Standing One Arm Bicep Curl With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'standing-one-arm-curl-over-incline-bench-with-dumbbell', displayName: 'Standing One Arm Curl Over Incline Bench With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'standing-one-arm-triceps-extension-with-dumbbell', displayName: 'Standing One Arm Triceps Extension With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'standing-overhead-triceps-extension-with-barbell', displayName: 'Standing Overhead Triceps Extension With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'standing-triceps-extension', displayName: 'Standing Triceps Extension', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'standing-triceps-extension-2', displayName: 'Standing Triceps Extension 2', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'static-neck-flexion-extension', displayName: 'Static Neck Flexion Extension', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight' },
  { imageKey: 'static-neck-side-flexion', displayName: 'Static Neck Side Flexion', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight' },
  { imageKey: 'stationary-abdominal-draw-in', displayName: 'Stationary Abdominal Draw In', category: 'Bodyweight', muscleGroup: 'Core', equipment: 'Bodyweight' },
  { imageKey: 'step-up-single-leg-balance-with-bicep-curl-using-dumbbells', displayName: 'Step Up Single Leg Balance With Bicep Curl Using Dumbbells', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell' },
  { imageKey: 'step-ups-with-barbell', displayName: 'Step Ups With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'step-ups-with-dumbbells', displayName: 'Step Ups With Dumbbells', category: 'Dumbbell', muscleGroup: 'Legs', equipment: 'Dumbbell' },
  { imageKey: 'stork-stance-bicep-curl-with-dumbbells', displayName: 'Stork Stance Bicep Curl With Dumbbells', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'straight-arm-dumbbell-pullover', displayName: 'Straight Arm Dumbbell Pullover', category: 'Dumbbell', muscleGroup: 'Back', equipment: 'Dumbbell' },
  { imageKey: 'straight-arm-push-down', displayName: 'Straight Arm Push Down', category: 'Cable', muscleGroup: 'Back', equipment: 'Cable' },
  { imageKey: 'supermans', displayName: 'Supermans', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight' },
  { imageKey: 'tate-press', displayName: 'Tate Press', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 't-bar-rows', displayName: 'T Bar Rows', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell' },
  { imageKey: 'thigh-abductor', displayName: 'Thigh Abductor', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'thigh-adductor', displayName: 'Thigh Adductor', category: 'Machine', muscleGroup: 'Legs', equipment: 'Machine' },
  { imageKey: 'tricep-dips', displayName: 'Tricep Dips', category: 'Bodyweight', muscleGroup: 'Arms', equipment: 'Bodyweight' },
  { imageKey: 'tricep-dips-using-body-weight', displayName: 'Tricep Dips Using Body Weight', category: 'Bodyweight', muscleGroup: 'Arms', equipment: 'Bodyweight' },
  { imageKey: 'triceps-extensions-using-machine', displayName: 'Triceps Extensions Using Machine', category: 'Machine', muscleGroup: 'Arms', equipment: 'Machine' },
  { imageKey: 'triceps-pushdown-with-cable', displayName: 'Triceps Pushdown With Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'triceps-pushdown-with-rope-and-cable', displayName: 'Triceps Pushdown With Rope And Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'triceps-pushdown-with-v-bar-and-cable', displayName: 'Triceps Pushdown With V Bar And Cable', category: 'Cable', muscleGroup: 'Arms', equipment: 'Cable' },
  { imageKey: 'two-arm-preacher-curl-with-dumbbell', displayName: 'Two Arm Preacher Curl With Dumbbell', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'underhand-pull-down', displayName: 'Underhand Pull Down', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine' },
  { imageKey: 'underhand-pull-downs', displayName: 'Underhand Pull Downs', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine' },
  { imageKey: 'upright-band-rows', displayName: 'Upright Band Rows', category: 'Cable', muscleGroup: 'Shoulders', equipment: 'Band' },
  { imageKey: 'upright-barbell-rows', displayName: 'Upright Barbell Rows', category: 'Barbell', muscleGroup: 'Shoulders', equipment: 'Barbell' },
  { imageKey: 'upright-cable-row', displayName: 'Upright Cable Row', category: 'Cable', muscleGroup: 'Shoulders', equipment: 'Cable' },
  { imageKey: 'v-bar-pull-down', displayName: 'V Bar Pull Down', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine' },
  { imageKey: 'walking-lunges', displayName: 'Walking Lunges', category: 'Bodyweight', muscleGroup: 'Legs', equipment: 'Bodyweight' },
  { imageKey: 'weighted-sissy-squat-with-weight-plate', displayName: 'Weighted Sissy Squat With Weight Plate', category: 'Bodyweight', muscleGroup: 'Legs', equipment: 'Bodyweight' },
  { imageKey: 'wide-grip-bench-press', displayName: 'Wide Grip Bench Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell' },
  { imageKey: 'wide-grip-chin-up', displayName: 'Wide Grip Chin Up', category: 'Bodyweight', muscleGroup: 'Back', equipment: 'Bodyweight' },
  { imageKey: 'wide-grip-decline-barbell-pullover', displayName: 'Wide Grip Decline Barbell Pullover', category: 'Barbell', muscleGroup: 'Back', equipment: 'Barbell' },
  { imageKey: 'wide-grip-decline-bench-press', displayName: 'Wide Grip Decline Bench Press', category: 'Barbell', muscleGroup: 'Chest', equipment: 'Barbell' },
  { imageKey: 'wide-grip-lat-pull-down', displayName: 'Wide Grip Lat Pull Down', category: 'Machine', muscleGroup: 'Back', equipment: 'Machine' },
  { imageKey: 'wide-grip-standing-biceps-curl-with-barbell', displayName: 'Wide Grip Standing Biceps Curl With Barbell', category: 'Barbell', muscleGroup: 'Arms', equipment: 'Barbell' },
  { imageKey: 'wide-stance-squat-with-barbell', displayName: 'Wide Stance Squat With Barbell', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'zecher-squats', displayName: 'Zecher Squats', category: 'Barbell', muscleGroup: 'Legs', equipment: 'Barbell' },
  { imageKey: 'zottman-curl-with-dumbbells', displayName: 'Zottman Curl With Dumbbells', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
  { imageKey: 'zottman-preacher-curl-with-dumbbells', displayName: 'Zottman Preacher Curl With Dumbbells', category: 'Dumbbell', muscleGroup: 'Arms', equipment: 'Dumbbell' },
];

module.exports = exercises;
