/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/shared/AllWorkoutsSlideUp`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/utils/pendingExercise`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/logs` | `/logs`; params?: Router.UnknownInputParams; } | { pathname: `/workout/active`; params?: Router.UnknownInputParams; } | { pathname: `/workout/add-exercise`; params?: Router.UnknownInputParams; } | { pathname: `/workout/create-template`; params?: Router.UnknownInputParams; } | { pathname: `/workout/finish`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/workout/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/shared/AllWorkoutsSlideUp`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/utils/pendingExercise`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/logs` | `/logs`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/active`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/add-exercise`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/create-template`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/finish`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/workout/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/shared/AllWorkoutsSlideUp${`?${string}` | `#${string}` | ''}` | `/../lib/utils/pendingExercise${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/logs${`?${string}` | `#${string}` | ''}` | `/logs${`?${string}` | `#${string}` | ''}` | `/workout/active${`?${string}` | `#${string}` | ''}` | `/workout/add-exercise${`?${string}` | `#${string}` | ''}` | `/workout/create-template${`?${string}` | `#${string}` | ''}` | `/workout/finish${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/shared/AllWorkoutsSlideUp`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/utils/pendingExercise`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/logs` | `/logs`; params?: Router.UnknownInputParams; } | { pathname: `/workout/active`; params?: Router.UnknownInputParams; } | { pathname: `/workout/add-exercise`; params?: Router.UnknownInputParams; } | { pathname: `/workout/create-template`; params?: Router.UnknownInputParams; } | { pathname: `/workout/finish`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/workout/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/workout/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
